### ISSUE TITLE
Seed does not take current year as default value

### ISSUE THREAD

**Issue by ancailliau** [blambeau/rqp2#2]
Typing `bin/rake db:seed` does not seed the database with the folder corresponding to the current year.

**Comment by blambeau** [comment]
I agree, it should. See here: https://github.com/blambeau/rqp2/blob/master/tasks/db.rake#L25-L34

Still, it would be easy to replace `'2014'` by `Time.now.year.to_s` but that does not follow the _academic_ year (I suppose the current seeds are in 2015, not 2016, right?)

**Comment by ancailliau** [comment]
Nope, I've put them in 2016. Fixed in the proposed commit.

**Comment by blambeau** [comment]
@ancailliau OK, great, please submit a pull request then, I'll merge that.

P.S. Possibly we want to add the 2016 seeds to the source code too?
